---
# Install flink packages

- name: unwanted packages are removed
  package:
    name: "{{ flink_packages_remove }}"
    state: absent
  become: true
  when: flink_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ flink_packages_repos }}"
    state: "{{ flink_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ flink_packages_prereq }}"
    state: "{{ flink_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ flink_packages_install }}"
    state: "{{ flink_packages_state }}"
  become: true
